# Generated by Django 4.2.5 on 2023-09-11 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_tag_color_remove_tag_slug_alter_tag_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tags',
            new_name='tag',
        ),
    ]
