# Generated by Django 4.2.5 on 2023-09-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_ingredient_remove_recipe_ingredient_ingredientrecipe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
        migrations.DeleteModel(
            name='TagRecipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
