# Generated by Django 4.2.5 on 2023-09-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_tag_options_remove_recipe_tags_alter_tag_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.TextField(default='eko'),
            preserve_default=False,
        ),
    ]
