# Generated by Django 4.2.5 on 2023-09-17 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_remove_recipe_tags_recipe_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagRecipe',
        ),
    ]
